name: 'GitOps Deploy Tag Action'
description: 'Updates image tag in target file'
inputs:
  gitops-repo:
    description: 'gitops repo to be updated'
    required: true
    default: ${DEPLOY_GITOPS_REPO}

  target-file:
    description: 'Target yaml file to replace tag'
    required: true

  docker-image-tag:
    description: 'docker image tag'
    required: true
    default: ${GITHUB_SHA::6}

runs:
  using: "composite"
  steps:
    - name: Checkout gitops
      run: |
        echo Checking out https://github.com/${{ inputs.gitops-repo }}.git
        rm -rf ./gitops_tmp
        git clone --depth 1 https://x-access-token:$DEPLOY_TOKEN@github.com/${{ inputs.gitops-repo }}.git ./gitops_tmp
      shell: bash

    - name: Update image tag
      working-directory: ./gitops_tmp
      run: |
        echo Setting \"${{ inputs.docker-image-tag }}\" tag in "${{ inputs.target-file }}"
        sed -i 's/tag: .*$/tag: "'${{ inputs.docker-image-tag }}'"/g' ${{ inputs.target-file }}
      shell: bash

    - name: Push changes to gitops
      working-directory: ./gitops_tmp
      run: |
        echo Pushing changes to ${{ inputs.gitops-repo }}
        git config user.email "ga-deployer@tietoevry.com"
        git config user.name "GA deployer"
        git add .
        git commit --allow-empty -m "Deploy \"${{ inputs.docker-image-tag }}\" tag for ${{ inputs.target-file }}"
        git push -u origin master
      shell: bash